/**
* Aksjesimulator model
* All prices are in 1/10000 NOK. I.e. a price of 10 000 = 1 NOK
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param price 
 * @param week Date of wednesday in the week
 */

data class HistoricalPricesWeekly (
    @Json(name = "price")
    val price: kotlin.Long,
    /* Date of wednesday in the week */
    @Json(name = "week")
    val week: java.time.LocalDate
)

