/**
* Aksjesimulator model
* All prices are in 1/10000 NOK. I.e. a price of 10 000 = 1 NOK
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param timestamp Transaction date and time
 * @param ticker 
 * @param amount Change in number of stocks on the account
 * @param price Price per stock, excluding fees
 * @param sumOfFees 
 */

data class Transaction (
    /* Transaction date and time */
    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime,
    @Json(name = "ticker")
    val ticker: kotlin.String,
    /* Change in number of stocks on the account */
    @Json(name = "amount")
    val amount: kotlin.Int,
    /* Price per stock, excluding fees */
    @Json(name = "price")
    val price: kotlin.Int,
    @Json(name = "sumOfFees")
    val sumOfFees: kotlin.Int
)

