/**
* Aksjesimulator model
* All prices are in 1/10000 NOK. I.e. a price of 10 000 = 1 NOK
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package no.aksjesimulator.domain.models


import com.squareup.moshi.Json

/**
 * 
 * @param ticker 
 * @param amount Number of stocks
 * @param gav Average price paid per stock, including fees
 */

data class AccountHolding (
    @Json(name = "ticker")
    val ticker: kotlin.String,
    /* Number of stocks */
    @Json(name = "amount")
    val amount: kotlin.Long,
    /* Average price paid per stock, including fees */
    @Json(name = "gav")
    val gav: kotlin.Long
)

