/**
* Aksjesimulator model
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package no.aksjesimulator.domain.models


import com.squareup.moshi.Json

/**
 * 
 * @param price 
 * @param month Date of the 1st of the month
 */

data class HistoricalPricesMonthly (
    @Json(name = "price")
    val price: kotlin.Double? = null,
    /* Date of the 1st of the month */
    @Json(name = "month")
    val month: java.time.LocalDate? = null
)

