/**
* Aksjesimulator model
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package no.aksjesimulator.domain.models


import com.squareup.moshi.Json

/**
 * 
 * @param timestamp 
 * @param price 
 * @param ticker 
 */

data class StockPrice (
    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime,
    @Json(name = "price")
    val price: kotlin.Double,
    @Json(name = "ticker")
    val ticker: kotlin.String
)

