/**
* Aksjesimulator model
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package no.aksjesimulator.domain.models

import no.aksjesimulator.domain.models.Account

import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param username 
 * @param password Deprecated. Will be replaced with hash+salt or something
 * @param accounts 
 * @param email 
 */

data class User (
    @Json(name = "id")
    val id: kotlin.Int,
    @Json(name = "username")
    val username: kotlin.String,
    /* Deprecated. Will be replaced with hash+salt or something */
    @Json(name = "password")
    val password: kotlin.String,
    @Json(name = "accounts")
    val accounts: kotlin.collections.List<Account>? = null,
    @Json(name = "email")
    val email: kotlin.String? = null
)

