openapi: 3.0.3
info:
  title: Aksjesimulator model
  version: 1.0.0
  description: All prices are in 1/10000 NOK. I.e. a price of 10 000 = 1 NOK
paths:
  /dummy:
    get:
      summary: Because paths section is required?
      responses:
        200:
          description: OK
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
          minLength: 3
          maxLength: 16
        password:
          type: string
          description: Deprecated. Will be replaced with hash+salt or something
        email:
          type: string
          nullable: true
    Account:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        name:
          type: string
        balance:
          type: integer
        commissionFlat:
          type: integer
        commissionPercentage:
          type: integer
        currencyFeePercentage:
          type: integer
    Transaction:
      type: object
      properties:
        accountId:
          type: integer
        timestamp: 
          type: string
          format: date-time
          description: Transaction date and time
          example: "2021-01-30T08:30:00Z"
        ticker:
          type: string
        amount:
          type: integer
          description: Change in number of stocks on the account
        price:
          type: integer
          description: Price per stock, excluding fees
        sumOfFees:
          type: integer
    AccountHolding:
      type: object
      properties:
        accountId:
          type: integer
        ticker: 
          type: string
        amount:
          type: integer
          description: Number of stocks
        gav:
          type: integer
          description: Average price paid per stock, including fees
    Ticker:
      type: object
      properties:
        ticker: 
          type: string
        name: 
          type: string
        exchange:
          type: string
    StockPrice:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        price: 
          type: integer
    HistoricalPrices:
      type: object
      properties:
        id:
          type: integer
        ticker:
          type: string
        daily:
          type: array
          items:
            type: object
            properties:
              price:
                type: integer
              date:
                type: string
                format: date
        weekly:
          type: array
          items:
            type: object
            properties:
              price:
                type: integer
              week:
                type: string
                format: date
                description: Date of wednesday in the week
        monthly:
          type: array
          items:
            type: object
            properties:
              price:
                type: integer
              month: 
                type: string
                format: date
                description: Date of the 1st of the month