openapi: 3.0.3
info:
  title: Aksjesimulator model
  version: 1.0.0
paths:
  /dummy:
    get:
      summary: Because paths section is required?
      responses:
        '200':
          description: OK
components:
  schemas:
    Transaction:
      type: object
      required:
        - timestamp
        - ticker
        - amount
        - price
        - sumOfFees
      properties:
        timestamp:
          type: string
          format: date-time
          nullable: false
          description: Transaction date and time
          example: '2021-01-30T08:30:00Z'
        ticker:
          type: string
        amount:
          type: integer
          format: int64
          description: Change in number of stocks on the account
        price:
          type: number
          format: double
          description: 'Price per stock, excluding fees'
        sumOfFees:
          type: number
          format: double
    AccountHolding:
      type: object
      required:
        - ticker
        - amount
        - gav
      properties:
        ticker:
          type: string
        amount:
          type: integer
          format: int64
          description: Number of stocks
        gav:
          type: number
          format: double
          description: 'Average price paid per stock, including fees'
    Ticker:
      type: object
      required:
        - ticker
        - name
        - exchange
      properties:
        ticker:
          type: string
        name:
          type: string
        exchange:
          type: string
    StockPrice:
      type: object
      required:
        - timestamp
        - price
        - ticker
      properties:
        timestamp:
          type: string
          format: date-time
        price:
          type: number
          format: double
        ticker:
          type: string
    HistoricalPrices:
      type: object
      required:
        - ticker
        - daily
        - weekly
        - monthly
      properties:
        ticker:
          type: string
        daily:
          type: array
          items:
            type: object
            required:
              - price
              - date
            properties:
              price:
                type: number
                format: double
              date:
                type: string
                format: date
        weekly:
          type: array
          items:
            type: object
            required:
              - price
              - week
            properties:
              price:
                type: number
                format: double
              week:
                type: string
                format: date
                description: Date of wednesday in the week
        monthly:
          type: array
          nullable: false
          items:
            type: object
            nullable: false
            properties:
              price:
                type: number
                format: double
                nullable: false
              month:
                type: string
                format: date
                nullable: false
                description: Date of the 1st of the month
    Account:
      type: object
      required:
        - id
        - name
        - balance
        - commissionFlat
        - commissionPercentage
        - currencyFeePercentage
        - transactions
        - holdings
      properties:
        id:
          type: integer
        name:
          type: string
        balance:
          type: number
          format: double
        commissionFeeMinimum:
          type: number
          format: float
          description: Minimum treshold for commissionFee. In NOK.
        commissionFee:
          type: number
          format: float
          description: Percentage of each trade
        currencySpread:
          type: number
          format: float
          description: Percentage of each trade
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
        holdings:
          type: array
          items:
            $ref: '#/components/schemas/AccountHolding'
    User:
      type: object
      required:
        - id
        - accounts
        - username
        - password
      properties:
        id:
          type: integer
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/Account'
        username:
          type: string
          minLength: 3
          maxLength: 14
        password:
          type: string
          description: Deprecated. Will be replaced with hash+salt or something
        email:
          type: string